apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pending-demo
  namespace: k8sgpt-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: k8sgpt-non-existent-storageclass
