apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-aiops-api-readonly
  labels:
    app.kubernetes.io/name: kube-aiops-api
    app.kubernetes.io/part-of: kube-aiops
    app.kubernetes.io/component: portal-backend
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - core.k8sgpt.ai
    resources:
      - results
    verbs:
      - get
      - list
      - watch
