apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-aiops-api
  namespace: kube-aiops-system
  labels:
    app.kubernetes.io/name: kube-aiops-api
    app.kubernetes.io/part-of: kube-aiops
    app.kubernetes.io/component: portal-backend
automountServiceAccountToken: true
