apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8sgpt
  namespace: k8sgpt-operator-system
  labels:
    app.kubernetes.io/name: k8sgpt
    app.kubernetes.io/component: analyzer
    app.kubernetes.io/part-of: kube-aiops
automountServiceAccountToken: true
